# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
